### ISSUE TITLE
Doom Emacs config

### ISSUE THREAD

**Issue by meedstrom** [alphapapa/prism.el#11]
Doom Emacs uses rainbow-delimiters-mode by default.  For ages, I was using it together with prism without realizing.  I'm fairly experienced with initfile stuff but missed it anyway, which shows how easy it may be to miss.  A hint in the README may be appropriate, or even a message printed when prism-mode turns on.

Now my use-package declaration has an extensive `remove-hook!` which you may also find useful to put in README.  Up to you.

``` emacs-lisp
(use-package prism
  :hook (prog-mode . prism-mode)
  :config
  (add-hook 'doom-load-theme-hook #'prism-set-colors)
  (remove-hook! (racket-mode
                 scheme-mode
                 sh-mode
                 clojure-mode
                 purescript-mode
                 rjsx-mode
                 typescript-mode
                 typescript-tsx-mode
                 TeX-update-style
                 zig
                 java-mode
                 c-mode-common
                 csharp-mode
                 lisp-mode)
    #'rainbow-delimiters-mode))

```

Since these hooks may change, a futureproof alternative is `(fset 'rainbow-delimiters-mode #'ignore)`.  Unfortunately simply disabling it with `(package! rainbow-delimiters :ignore t)` is not supported; it's considered part of Doom's core.

EDIT: I guess an even better alternative would be if `prism-mode` toggles `rainbow-delimiters-mode`.  Any way the user can make it do that?

Unfortunately this is not so easy as the following advice will not run sufficiently late for Doom (if prism-mode is on prog-mode-hook)... but at that point it's more a Doom bug.

``` emacs-lisp
(advice-add #'prism-mode :after
              (defun my-turn-off-rainbow-delimiters (&rest _args)
                (rainbow-delimiters-mode 0)))
```

**Comment by alphapapa** [comment]
I hope you'll understand, but I don't accommodate Spacemacs or DOOM in my readmes.  Users who choose to use those systems should refer to those projects' documentation and configure them accordingly.

> I guess an even better alternative would be if prism-mode toggles rainbow-delimiters-mode.

It wouldn't be appropriate for `prism` to interfere with other packages like that.

**Comment by meedstrom** [comment]
As you wish.
