### ISSUE TITLE
Use more builtins for examples

### ISSUE THREAD

**Issue by nickdrozd** [alphapapa/prism.el#2]
A lot of the example color configurations use `solarized-with-color-variables`, but that isn't a builtin and it isn't obvious where it comes from. It took me a while to figure out that a list of strings is required.

It might be a good idea to include some default configurations.

**Comment by alphapapa** [comment]
Thanks for pointing that out.  I've updated the docs and put the non-Solarized examples first, as well as explained the `:colors` argument.  What do you think?

**Comment by nickdrozd** [comment]
Better! I think the first one should be a plain list of colors, eg `'("red" "green" "blue" ...)`. Using faces doesn't seem suitable to me for the first example.
