### ISSUE TITLE
Color scheme vanishes

### ISSUE THREAD

**Issue by monroth** [alphapapa/prism.el#21]
After certain events (not sure exactly what causes it - usually it is after some buffer is opened; i'll post more if i'll see any more patterns) color scheme in prism-mode vanishes and it starts to color everything in gray
![image](https://github.com/alphapapa/prism.el/assets/28282020/d88d5f0b-b930-4352-aac0-05eb74686a0c)
Using prism-set-colors (for example, in a way of recompiling part of .emacs file) does not change anything.
However, prism-randomize-colors still work and produce new random color scheme. The only way i found to return original (specified in .emacs) color scheme that i found is to restart emacs.

**Comment by alphapapa** [comment]
That likely indicates that another package is overriding the faces.  You'll have to look carefully at which other modes you're activating in those buffers.

Also, FYI compiling your .emacs or init.el file isn't generally recommended.  It can sometimes lead to strange behavior, and the performance gains are usually insignificant.

See also the command `font-lock-update`.  A well-behaved mode should remove any face properties when disabled, and `font-lock-update` should then refontify the buffer accordingly.

**Comment by monroth** [comment]
it seems that dir-treeview breaks colors when it loads it's theme

**Comment by alphapapa** [comment]
Ok, you should probably report that bug to its author.  :)
