### ISSUE TITLE
Background color not always defined on terminal

### ISSUE THREAD

**Issue by bram85** [alphapapa/prism.el#22]
Like you already experienced (and [fixed](https://github.com/alphapapa/ement.el/commit/74d10eb1301a048c2116bf36c0674b5b210b8dc3#diff-2bd6ac471a2d83fd4ece131b81185e0b6d5098a48563d3aee96bcd8987222914R692)) with ement.el, the same thing could happen in prism.el.

There are a few [instances ](https://github.com/alphapapa/prism.el/blob/169b49afa91e69d35b8756df49ed3ca06f418d35/prism.el#L803) of `(face-attribute 'default :background)` which may be "unspecified-bg", which is a color that cannot be blended.

This results in error messages at startup when running `emacs -nw` in some terminals:

`prism-blend: Wrong type argument: number-or-marker-p, nil`

**Comment by alphapapa** [comment]
Thanks.
