### ISSUE TITLE
lag with common lisp 

### ISSUE THREAD

**Issue by Dapuva76** [alphapapa/prism.el#3]
Occasionally I delete one parentheses too many, and suddenly the whole document is part of a function. When this happens, emacs becomes unresponsive for several seconds, due to the fact (I guess) that the colors need to be re-calculated for the whole document.

**Comment by alphapapa** [comment]
Yes, this happens to me as well when a Lisp form is too large.  It needs to be optimized for this case.

**Comment by alphapapa** [comment]
This should have been fixed by https://github.com/alphapapa/prism.el/commit/e41c9194d7055dae832c6b66f07d30dad781cef2.
