### ISSUE TITLE
Consider adding defcustom prism-parens-alpha

### ISSUE THREAD

**Issue by shipmints** [alphapapa/prism.el#30]
Thanks for prism. Enjoying it so far.

I overrode ```parens-fn``` merely to adjust the alpha level. Perhaps for most users it would be easier to use a ```prism-parens-alpha``` variable vs copying the default function outright?

I suppose same for adding ```prism-comments-alpha```?

**Comment by alphapapa** [comment]
I'm glad you're enjoying it.

I'd rather not add options like these, because then users will want corresponding `-this` and `-that` options, and that means a lot more complexity than just calling a function.

**Comment by shipmints** [comment]
No problem. It's already complex enough.
