### ISSUE TITLE
prefix-string-p error in prism-set-colors

### ISSUE THREAD

**Issue by seblemaguer** [alphapapa/prism.el#5]
Hello,

by adding the following `--remove` clause in the following line:

https://github.com/alphapapa/prism.el/blob/f7b8da440da1864ea85392794243eb9844f52f39/prism.el#L735

it causes to crash with an `wrong number of arguments` exception. I replaced the previous line with

```elisp
(--remove (string-prefix-p "unspecified-" (format "%S" it)))
```

and it seems to work but I don't really know if that is what you wanted to do. 

PS: the use of format is because there are symbols and raw color code as strings.

**Comment by alphapapa** [comment]
Oops, thanks.  I pushed a fix that I think is what I should have done in the first place.
