### ISSUE TITLE
Feature: paren-face compatibility

### ISSUE THREAD

**Issue by berkan** [alphapapa/prism.el#7]
Hello,

Thank you for prism.

Is it possible to make it compatible with [paren-face](https://github.com/tarsius/paren-face)? I'm guessing that means prism not including the parentheses for fontification so that those from paren-face aren't overridden, but I don't know how much work that involves.

I'm using paren-face to hide parentheses in javascript code, which makes it more pleasant to work with :)

Thanks again
Berkan

**Comment by alphapapa** [comment]
The solution to this might be as simple as changing the order in which you activate `prism-mode` and `paren-face-mode`.

If that doesn't solve it, then I might be willing to consider this feature, but since it would require many changes to complex code, I'd probably be reluctant to implement it.

**Comment by berkan** [comment]
Tried it, and prism overrides paren-face regardless of which one is activated first.

I feared that isolating parentheses may require non-trivial changes to the code. Still, thanks for considering.

**Comment by berkan** [comment]
Upon further inspection, two small modifications to `paren-face-mode` so that it can coexist with others was all it took [*]. Putting it here in case somebody else finds it useful:

```
(define-minor-mode paren-face-mode
  "Use a dedicated face just for parentheses."
  :lighter paren-face-mode-lighter
  (let ((keywords `((,paren-face-regexp 0 'parenthesis prepend) ))) ;; OVERRIDE=prepend
    (if paren-face-mode
        (font-lock-add-keywords  nil keywords t) ;; HOW=t
      (font-lock-remove-keywords nil keywords)))
...
```

[This](https://emacs.stackexchange.com/a/59914) is a good explanation for a similar case.

[*] also, turn on `prism-mode` first, then `paren-face-mode`.
